openapi: "3.0.3"

info:
  title: "Ktor Sample App JWT"
  description: "A JSON API that allows you to view and add customers with authentication"
  version: "0.0.1"

servers:
  - url: "http://localhost:8080"

paths:
  /api/auth:
    post:
      description: "Get a token for user"
      tags:
        - auth
      requestBody:
        description: "A JSON object containing login information"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"
        "404":
          description: "User not found"

  /api/user:
    post:
      description: "Create a new user"
      tags:
        - user
      requestBody:
        description: "A JSON object containing user information"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserRequest"
      responses:
        "201":
          description: "Created"
        "409":
          description: "User already exists"
    get:
      description: "Get all users"
      tags:
        - user
      security:
        - bearerAuth: []
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Users"
        "401":
          description: "User not found"
          $ref: "#/components/responses/UnauthorizedError"

  /api/user/{id}:
    get:
      description: "Returns a user by its ID"
      tags:
        - user
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
      security:
        - bearerAuth: []
      responses:
        "200":
          description: "OK"
          content:
            'application/json':
              schema:
                $ref: "#/components/schemas/UserResponse"
        "401":
          description: "User not found"
          $ref: "#/components/responses/UnauthorizedError"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  responses:
    UnauthorizedError:
      description: "Token is not valid or has expired"

  schemas:
    LoginRequest:
      type: "object"
      properties:
        username:
          type: "string"
        password:
          type: "string"
    LoginResponse:
      type: "object"
      properties:
        token:
          type: "string"

    UserRequest:
      type: "object"
      properties:
        username:
          type: "string"
        password:
          type: "string"
    UserResponse:
      type: "object"
      properties:
        id:
          type: "string"
        username:
          type: "string"
    Users:
      type: "array"
      items:
        type: "object"
        properties:
          id:
            type: "string"
          username:
            type: "string"

security:
  - bearerAuth: []

tags:
  - name: auth
    description: "Authentication"
  - name: user
    description: "User operations"
